data:
    name: 'coco'
#    labels: superpoint_base199_homoAdapt_coco_top600_resize/predictions # Complete with your export labels
#    labels: superpoint_homoAdapt100_coco_det199_top600_resize/predictions # Complete with your export labels
#     labels: superpoint_homoAdapt100_coco_det255_top600_resize/predictions
#    labels: magicpoint_syn100k_homoAdapt100_coco/predictions
#     labels: coco_test # Complete with your export labels
    cache_in_memory: false
    validation_size: 192
    preprocessing:
        resize: [240, 320]

    warped_pair:
        enable: true
        params:
            translation: true
            rotation: false
            scaling: false
            perspective: false
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            patch_ratio: 0.85
            max_angle: 1.57
            allow_artifacts: true # true
        valid_border_margin: 3

    augmentation:
        photometric:
            enable: true
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.3, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                motion_blur: {max_kernel_size: 2} # origin 7
        homographic:
            enable: true
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                patch_ratio: 0.85
                max_angle: 1.57
                allow_artifacts: true
            valid_border_margin: 3

model:
    name: 'magic_point'
    batch_size: 2 # 32
    eval_batch_size: 32
    learning_rate: 0.001
    detection_threshold: 0.001 # 0.015
    nms: 4
    # top_k: 300

retrain: false # set true for new model
reset_iter: true
train_iter: 200000
validation_interval: 1000
warp_scale: 3 # inverse scale (>1)


# pretrained: 'logs/magic-point_synth_4/checkpoints/superPointNet_199_checkpoint.pth.tar'
# pretrained: 'logs/magicpoint_coco/checkpoints/superPointNet_255_checkpoint.pth.tar'
# pretrained: 'logs/superpoint_coco/checkpoints/superPointNet_260_checkpoint.pth.tar'
# pretrained: 'logs/magic-point_synth_4/checkpoints/superPointNet_199_checkpoint.pth.tar'
# pretrained: 'logs/magicpoint_coco/checkpoints/superPointNet_18226_checkpoint.pth.tar'   
# pretrained: 'logs/magicpoint_coco4/checkpoints/superPointNet_200032_checkpoint.pth.tar'

# pretrained: 'logs/magicpoint_coco6/checkpoints/superPointNet_5384_checkpoint.pth.tar'

# pretrained: 'logs/superpoint_coco/checkpoints/superPointNet_79_checkpoint.pth.tar'
# pretrained: 'logs/magicpoint_synth3/checkpoints/superPointNet_22693_checkpoint.pth.tar'
# pretrained: 'logs/superpoint_coco/checkpoints/superPointNet_247_checkpoint.pth.tar'
#pretrained: 'logs/superpoint_coco/checkpoints/superPointNet_998_checkpoint.pth.tar'
#pretrained: 'pretrained/superpoint_v1.pth'

#pretrained: 'logs/magicpoint_synth/checkpoints/superPointNet_1_checkpoint.pth.tar'
pretrained: 'logs/magicpoint_coco5/checkpoints/superPointNet_89082_checkpoint.pth.tar'



