data:
    name: 'patches_dataset'
    dataset: 'kitti'  # 'coco' 'hpatches'
    export_folder: 'train'
    alteration: 'all'  # 'all' 'i' 'v'
    preprocessing:
    root: 'datasets/kitti_wVal'
#        resize: [240, 320]  # [
#        resize: [192, 624]  # hand defined
        # resize: [96, 312]  # hand defined
    # gaussian_label:
    #     enable: false # false
    #     sigma: 1.
    # homography_adaptation:
    #     enable: true
    #     num: 10 # 100
    #     aggregation: 'sum'
    #     filter_counts: 0
    #     homographies:
    #         params:
    #             translation: true
    #             rotation: true
    #             scaling: true
    #             perspective: true
    #             scaling_amplitude: 0.2
    #             perspective_amplitude_x: 0.2
    #             perspective_amplitude_y: 0.2
    #             allow_artifacts: true
    #             patch_ratio: 0.85
#    name: 'coco'
#    cache_in_memory: false
#    validation_size: 100
model:
    name: 'SuperPointNet_gauss2'
    params: {}
    batch_size: 1
    detection_threshold: 0.015 # 0.015
    nms: 4
    # top_k: 600 # I didn' do so for now
    nn_thresh: 1.2 # 0.7
    # subpixel: false
    subpixel:
        enable: false
        params:
            subpixel_channel: 2
    pretrained: '../deepSfm/logs/superpoint_kitti_heat2_0/checkpoints/superPointNet_50000_checkpoint.pth.tar'
    # pretrained: '../deepSfm/logs/superpoint_coco_heat2_0/checkpoints/superPointNet_170000_checkpoint.pth.tar'

evaluations:
    params:
        ransac_thresh: 0.1 # threshold for 5-point, and 8-point, previous: 0.1

    random_frame: true # must be true!!
    starting_frame: 500 # 500
    frame_diff: 1 # 3

    round: false
    block_center:
        enable: false
        size: [100, 200] # rectangle
        # height: 100

    iter_max: 3 # 100
    five_point: false
    use_est_E: false
    # other_settings: ''
    # other_settings: 'use est E for % of correspondence inliers'
    other_settings: 'use gt E for % of correspondence inliers'

front_end_model: 'Val_model_heatmap'  # 'Train_model_frontend'

###### sp pretrained ######
feature_mode: 2 # 1 for sift, 2 for superpoint
save:
    enable: true
    path: 'logs/experiment_kitti_sequence_sp_pretrained.txt'
pretrained: '../deepSfm/pretrained/superpoint_v1.pth'

###### sp our model ######
feature_mode: 2 # 1 for sift, 2 for superpoint
save:
    enable: true
    path: 'logs/experiment_kitti_sequence_sp_our_model.txt'
pretrained: '../deepSfm/logs/superpoint_coco40_2/checkpoints/superPointNet_170000_checkpoint.pth.tar'
# pretrained: '../deepSfm/logs/superpoint_kitti40_1/checkpoints/superPointNet_10000_checkpoint.pth.tar'

###### sift pretrained ######
feature_mode: 1 # 1 for sift, 2 for superpoint
save:
    enable: true
    path: 'logs/experiment_kitti_sequence_sift.txt'


###### visualization ######
###### sift pretrained ######
feature_mode: 2 # 1 for sift, 2 for superpoint
save:
    enable: false
    path: ''
# # pretrained: '../deepSfm/logs/superpoint_kitti40_1/checkpoints/superPointNet_50000_checkpoint.pth.tar'
# pretrained: '../deepSfm/logs/superpoint_coco40_16/checkpoints/superPointNet_170000_checkpoint.pth.tar'
# pretrained: '../deepSfm/logs/superpoint_kitti_heat2_0/checkpoints/superPointNet_50000_checkpoint.pth.tar'
csv_file: 'logs/result_table.csv'



