data:
    name: 'synthetic_shapes'
    suffix: 'v6'
    primitives: 'all'
    truncate: {draw_ellipses: 0.3, draw_stripes: 0.2, gaussian_noise: 0.1}
    cache_in_memory: true
    validation_size: 96
    labels: magic-point_coco-export2
    augmentation:
        photometric:
            enable: false
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur']
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                motion_blur: {max_kernel_size: 3}
        homographic:
            enable: false  # not implemented
    warped_pair:
        enable: true
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.25
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            patch_ratio: 0.85
            max_angle: 1.57
            allow_artifacts: false
        valid_border_margin: 3
model:
    name: 'super_point'
    batch_size: 3
    eval_batch_size: 3
    learning_rate: 0.001
    lambda_d: 250
    positive_margin: 1
    negative_margin: 0.2
    lambda_loss: 0.0001
    detection_threshold: 0.001 # 1/65
    nms: 4
    top_k: 600
retrain: true # set true for new model
reset_iter: true
# pretrained: 'pretrained/superpoint_v1.pth'
#pretrained_type: ''
#pretrained: 'logs/superpoint_syn/checkpoints/superPointNet_6000_checkpoint.pth.tar'
#pretrained: 'logs/magic-point_synth_4/checkpoints/superPointNet_199_checkpoint.pth.tar'
# pretrained_type: 'full'
train_iter: 100000
validation_interval: 3000
eval_iter: 50
